/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainersIndexRouteImport } from './routes/trainers.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TrainersUsernameRouteImport } from './routes/trainers.$username'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PaymentCompleteRouteImport } from './routes/payment.complete'
import { Route as DevHeaderPreviewRouteImport } from './routes/dev.header-preview'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTrainerProfileRouteImport } from './routes/_authenticated/trainer.profile'
import { Route as AuthenticatedCreatorDashboardRouteImport } from './routes/_authenticated/creator.dashboard'
import { Route as AuthenticatedAdminWebsitePreviewRouteImport } from './routes/_authenticated/admin/website-preview'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin/website'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin/webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTransformationsRouteImport } from './routes/_authenticated/admin/transformations'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedAdminTrainersRouteImport } from './routes/_authenticated/admin/trainers'
import { Route as AuthenticatedAdminTipsRouteImport } from './routes/_authenticated/admin/tips'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'
import { Route as AuthenticatedAdminStrikesRouteImport } from './routes/_authenticated/admin/strikes'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin/security'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin/roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin/refunds'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin/posts'
import { Route as AuthenticatedAdminPoliciesRouteImport } from './routes/_authenticated/admin/policies'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPaymentSettingsRouteImport } from './routes/_authenticated/admin/payment-settings'
import { Route as AuthenticatedAdminPaymentGatewaysRouteImport } from './routes/_authenticated/admin/payment-gateways'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin/moderation'
import { Route as AuthenticatedAdminLanguagesRouteImport } from './routes/_authenticated/admin/languages'
import { Route as AuthenticatedAdminEarningsRouteImport } from './routes/_authenticated/admin/earnings'
import { Route as AuthenticatedAdminDisputesRouteImport } from './routes/_authenticated/admin/disputes'
import { Route as AuthenticatedAdminDemoRouteImport } from './routes/_authenticated/admin/demo'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated/admin/countries'
import { Route as AuthenticatedAdminCommunityRouteImport } from './routes/_authenticated/admin/community'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin/comments'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin/audit-logs'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksPaypalRouteImport } from './routes/api/public/webhooks/paypal'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIndexRoute = TrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersUsernameRoute = TrainersUsernameRouteImport.update({
  id: '/trainers/$username',
  path: '/trainers/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCompleteRoute = PaymentCompleteRouteImport.update({
  id: '/payment/complete',
  path: '/payment/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHeaderPreviewRoute = DevHeaderPreviewRouteImport.update({
  id: '/dev/header-preview',
  path: '/dev/header-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedTrainerProfileRoute =
  AuthenticatedTrainerProfileRouteImport.update({
    id: '/trainer/profile',
    path: '/trainer/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatorDashboardRoute =
  AuthenticatedCreatorDashboardRouteImport.update({
    id: '/creator/dashboard',
    path: '/creator/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWebsitePreviewRoute =
  AuthenticatedAdminWebsitePreviewRouteImport.update({
    id: '/website-preview',
    path: '/website-preview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTransformationsRoute =
  AuthenticatedAdminTransformationsRouteImport.update({
    id: '/transformations',
    path: '/transformations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrainersRoute =
  AuthenticatedAdminTrainersRouteImport.update({
    id: '/trainers',
    path: '/trainers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTipsRoute = AuthenticatedAdminTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStrikesRoute =
  AuthenticatedAdminStrikesRouteImport.update({
    id: '/strikes',
    path: '/strikes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPoliciesRoute =
  AuthenticatedAdminPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentSettingsRoute =
  AuthenticatedAdminPaymentSettingsRouteImport.update({
    id: '/payment-settings',
    path: '/payment-settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentGatewaysRoute =
  AuthenticatedAdminPaymentGatewaysRouteImport.update({
    id: '/payment-gateways',
    path: '/payment-gateways',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLanguagesRoute =
  AuthenticatedAdminLanguagesRouteImport.update({
    id: '/languages',
    path: '/languages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEarningsRoute =
  AuthenticatedAdminEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDisputesRoute =
  AuthenticatedAdminDisputesRouteImport.update({
    id: '/disputes',
    path: '/disputes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDemoRoute = AuthenticatedAdminDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommunityRoute =
  AuthenticatedAdminCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaypalRoute = ApiPublicWebhooksPaypalRouteImport.update({
  id: '/api/public/webhooks/paypal',
  path: '/api/public/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qa': typeof AuthenticatedQaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/dev/header-preview': typeof DevHeaderPreviewRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/trainers/': typeof TrainersIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/demo': typeof AuthenticatedAdminDemoRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/languages': typeof AuthenticatedAdminLanguagesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payment-gateways': typeof AuthenticatedAdminPaymentGatewaysRoute
  '/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/strikes': typeof AuthenticatedAdminStrikesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tips': typeof AuthenticatedAdminTipsRoute
  '/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/transformations': typeof AuthenticatedAdminTransformationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin/website-preview': typeof AuthenticatedAdminWebsitePreviewRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qa': typeof AuthenticatedQaRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/dev/header-preview': typeof DevHeaderPreviewRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/trainers': typeof TrainersIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/demo': typeof AuthenticatedAdminDemoRoute
  '/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/admin/languages': typeof AuthenticatedAdminLanguagesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/payment-gateways': typeof AuthenticatedAdminPaymentGatewaysRoute
  '/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/strikes': typeof AuthenticatedAdminStrikesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tips': typeof AuthenticatedAdminTipsRoute
  '/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/admin/transformations': typeof AuthenticatedAdminTransformationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin/website-preview': typeof AuthenticatedAdminWebsitePreviewRoute
  '/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/shorts': typeof ShortsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/dev/header-preview': typeof DevHeaderPreviewRoute
  '/payment/complete': typeof PaymentCompleteRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/trainers/$username': typeof TrainersUsernameRoute
  '/u/$username': typeof UUsernameRoute
  '/trainers/': typeof TrainersIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/community': typeof AuthenticatedAdminCommunityRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/demo': typeof AuthenticatedAdminDemoRoute
  '/_authenticated/admin/disputes': typeof AuthenticatedAdminDisputesRoute
  '/_authenticated/admin/earnings': typeof AuthenticatedAdminEarningsRoute
  '/_authenticated/admin/languages': typeof AuthenticatedAdminLanguagesRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/payment-gateways': typeof AuthenticatedAdminPaymentGatewaysRoute
  '/_authenticated/admin/payment-settings': typeof AuthenticatedAdminPaymentSettingsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/strikes': typeof AuthenticatedAdminStrikesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/tips': typeof AuthenticatedAdminTipsRoute
  '/_authenticated/admin/trainers': typeof AuthenticatedAdminTrainersRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/admin/transformations': typeof AuthenticatedAdminTransformationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/_authenticated/admin/website-preview': typeof AuthenticatedAdminWebsitePreviewRoute
  '/_authenticated/creator/dashboard': typeof AuthenticatedCreatorDashboardRoute
  '/_authenticated/trainer/profile': typeof AuthenticatedTrainerProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/feed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/home'
    | '/library'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/qa'
    | '/settings'
    | '/wallet'
    | '/dev/header-preview'
    | '/payment/complete'
    | '/posts/$postId'
    | '/trainers/$username'
    | '/u/$username'
    | '/trainers/'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/community'
    | '/admin/countries'
    | '/admin/demo'
    | '/admin/disputes'
    | '/admin/earnings'
    | '/admin/languages'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/payment-gateways'
    | '/admin/payment-settings'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/posts'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/strikes'
    | '/admin/subscriptions'
    | '/admin/tips'
    | '/admin/trainers'
    | '/admin/transactions'
    | '/admin/transformations'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/website'
    | '/admin/website-preview'
    | '/creator/dashboard'
    | '/trainer/profile'
    | '/admin/'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/feed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/home'
    | '/library'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/qa'
    | '/settings'
    | '/wallet'
    | '/dev/header-preview'
    | '/payment/complete'
    | '/posts/$postId'
    | '/trainers/$username'
    | '/u/$username'
    | '/trainers'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/community'
    | '/admin/countries'
    | '/admin/demo'
    | '/admin/disputes'
    | '/admin/earnings'
    | '/admin/languages'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/payment-gateways'
    | '/admin/payment-settings'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/policies'
    | '/admin/posts'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/strikes'
    | '/admin/subscriptions'
    | '/admin/tips'
    | '/admin/trainers'
    | '/admin/transactions'
    | '/admin/transformations'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/website'
    | '/admin/website-preview'
    | '/creator/dashboard'
    | '/trainer/profile'
    | '/admin'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/explore'
    | '/feed'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/shorts'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/qa'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/dev/header-preview'
    | '/payment/complete'
    | '/posts/$postId'
    | '/trainers/$username'
    | '/u/$username'
    | '/trainers/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/community'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/demo'
    | '/_authenticated/admin/disputes'
    | '/_authenticated/admin/earnings'
    | '/_authenticated/admin/languages'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/payment-gateways'
    | '/_authenticated/admin/payment-settings'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/policies'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/strikes'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/tips'
    | '/_authenticated/admin/trainers'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/admin/transformations'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/_authenticated/admin/website'
    | '/_authenticated/admin/website-preview'
    | '/_authenticated/creator/dashboard'
    | '/_authenticated/trainer/profile'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShortsRoute: typeof ShortsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  DevHeaderPreviewRoute: typeof DevHeaderPreviewRoute
  PaymentCompleteRoute: typeof PaymentCompleteRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  TrainersUsernameRoute: typeof TrainersUsernameRoute
  UUsernameRoute: typeof UUsernameRoute
  TrainersIndexRoute: typeof TrainersIndexRoute
  ApiPublicWebhooksPaypalRoute: typeof ApiPublicWebhooksPaypalRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/': {
      id: '/trainers/'
      path: '/trainers'
      fullPath: '/trainers/'
      preLoaderRoute: typeof TrainersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$username': {
      id: '/trainers/$username'
      path: '/trainers/$username'
      fullPath: '/trainers/$username'
      preLoaderRoute: typeof TrainersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/complete': {
      id: '/payment/complete'
      path: '/payment/complete'
      fullPath: '/payment/complete'
      preLoaderRoute: typeof PaymentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/header-preview': {
      id: '/dev/header-preview'
      path: '/dev/header-preview'
      fullPath: '/dev/header-preview'
      preLoaderRoute: typeof DevHeaderPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/trainer/profile': {
      id: '/_authenticated/trainer/profile'
      path: '/trainer/profile'
      fullPath: '/trainer/profile'
      preLoaderRoute: typeof AuthenticatedTrainerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creator/dashboard': {
      id: '/_authenticated/creator/dashboard'
      path: '/creator/dashboard'
      fullPath: '/creator/dashboard'
      preLoaderRoute: typeof AuthenticatedCreatorDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/website-preview': {
      id: '/_authenticated/admin/website-preview'
      path: '/website-preview'
      fullPath: '/admin/website-preview'
      preLoaderRoute: typeof AuthenticatedAdminWebsitePreviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transformations': {
      id: '/_authenticated/admin/transformations'
      path: '/transformations'
      fullPath: '/admin/transformations'
      preLoaderRoute: typeof AuthenticatedAdminTransformationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trainers': {
      id: '/_authenticated/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AuthenticatedAdminTrainersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tips': {
      id: '/_authenticated/admin/tips'
      path: '/tips'
      fullPath: '/admin/tips'
      preLoaderRoute: typeof AuthenticatedAdminTipsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/strikes': {
      id: '/_authenticated/admin/strikes'
      path: '/strikes'
      fullPath: '/admin/strikes'
      preLoaderRoute: typeof AuthenticatedAdminStrikesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/policies': {
      id: '/_authenticated/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payment-settings': {
      id: '/_authenticated/admin/payment-settings'
      path: '/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AuthenticatedAdminPaymentSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payment-gateways': {
      id: '/_authenticated/admin/payment-gateways'
      path: '/payment-gateways'
      fullPath: '/admin/payment-gateways'
      preLoaderRoute: typeof AuthenticatedAdminPaymentGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/languages': {
      id: '/_authenticated/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AuthenticatedAdminLanguagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/earnings': {
      id: '/_authenticated/admin/earnings'
      path: '/earnings'
      fullPath: '/admin/earnings'
      preLoaderRoute: typeof AuthenticatedAdminEarningsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/disputes': {
      id: '/_authenticated/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/demo': {
      id: '/_authenticated/admin/demo'
      path: '/demo'
      fullPath: '/admin/demo'
      preLoaderRoute: typeof AuthenticatedAdminDemoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/community': {
      id: '/_authenticated/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AuthenticatedAdminCommunityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paypal': {
      id: '/api/public/webhooks/paypal'
      path: '/api/public/webhooks/paypal'
      fullPath: '/api/public/webhooks/paypal'
      preLoaderRoute: typeof ApiPublicWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminCommunityRoute: typeof AuthenticatedAdminCommunityRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminDemoRoute: typeof AuthenticatedAdminDemoRoute
  AuthenticatedAdminDisputesRoute: typeof AuthenticatedAdminDisputesRoute
  AuthenticatedAdminEarningsRoute: typeof AuthenticatedAdminEarningsRoute
  AuthenticatedAdminLanguagesRoute: typeof AuthenticatedAdminLanguagesRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPaymentGatewaysRoute: typeof AuthenticatedAdminPaymentGatewaysRoute
  AuthenticatedAdminPaymentSettingsRoute: typeof AuthenticatedAdminPaymentSettingsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPoliciesRoute: typeof AuthenticatedAdminPoliciesRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStrikesRoute: typeof AuthenticatedAdminStrikesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminTipsRoute: typeof AuthenticatedAdminTipsRoute
  AuthenticatedAdminTrainersRoute: typeof AuthenticatedAdminTrainersRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
  AuthenticatedAdminTransformationsRoute: typeof AuthenticatedAdminTransformationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRoute
  AuthenticatedAdminWebsitePreviewRoute: typeof AuthenticatedAdminWebsitePreviewRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
    AuthenticatedAdminCommunityRoute: AuthenticatedAdminCommunityRoute,
    AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
    AuthenticatedAdminDemoRoute: AuthenticatedAdminDemoRoute,
    AuthenticatedAdminDisputesRoute: AuthenticatedAdminDisputesRoute,
    AuthenticatedAdminEarningsRoute: AuthenticatedAdminEarningsRoute,
    AuthenticatedAdminLanguagesRoute: AuthenticatedAdminLanguagesRoute,
    AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminPaymentGatewaysRoute:
      AuthenticatedAdminPaymentGatewaysRoute,
    AuthenticatedAdminPaymentSettingsRoute:
      AuthenticatedAdminPaymentSettingsRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminPoliciesRoute: AuthenticatedAdminPoliciesRoute,
    AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
    AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
    AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminStrikesRoute: AuthenticatedAdminStrikesRoute,
    AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
    AuthenticatedAdminTipsRoute: AuthenticatedAdminTipsRoute,
    AuthenticatedAdminTrainersRoute: AuthenticatedAdminTrainersRoute,
    AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
    AuthenticatedAdminTransformationsRoute:
      AuthenticatedAdminTransformationsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
    AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRoute,
    AuthenticatedAdminWebsitePreviewRoute:
      AuthenticatedAdminWebsitePreviewRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedCreatorDashboardRoute: typeof AuthenticatedCreatorDashboardRoute
  AuthenticatedTrainerProfileRoute: typeof AuthenticatedTrainerProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedCreatorDashboardRoute: AuthenticatedCreatorDashboardRoute,
  AuthenticatedTrainerProfileRoute: AuthenticatedTrainerProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShortsRoute: ShortsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  DevHeaderPreviewRoute: DevHeaderPreviewRoute,
  PaymentCompleteRoute: PaymentCompleteRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  TrainersUsernameRoute: TrainersUsernameRoute,
  UUsernameRoute: UUsernameRoute,
  TrainersIndexRoute: TrainersIndexRoute,
  ApiPublicWebhooksPaypalRoute: ApiPublicWebhooksPaypalRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
